### ISSUE TITLE
Edit在启动一段时间后闪退

### ISSUE THREAD

**Issue by Node000** [LingFeng-bbben/MajdataView#172]
系统为win11
Edit在启动一段时间后自动闪退，View无事发生。
报错如下：
```
Application: MajdataEdit.exe
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: 不可恢复的系统错误。
Stack:
   at System.Environment.FailFast(System.String)
   at MS.Internal.Invariant.FailFast(System.String, System.String)
   at System.Windows.Documents.SplayTreeNode.get_Role()
   at System.Windows.Documents.SplayTreeNode.Splay()
   at System.Windows.Documents.SplayTreeNode.GetMinSibling()
   at System.Windows.Documents.TextPointer.GetAdjacentSiblingNode(System.Windows.Documents.TextTreeNode, System.Windows.Documents.ElementEdge, System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.GetAdjacentNode(System.Windows.Documents.TextTreeNode, System.Windows.Documents.ElementEdge, System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.GetElement(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.GetElementType(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointerBase.IsBeforeFirstTable(System.Windows.Documents.ITextPointer)
   at System.Windows.Documents.TextPointerBase.IsAtNormalizedPosition(System.Windows.Documents.ITextPointer, Boolean)
   at System.Windows.Documents.TextPointerBase.NormalizePosition(System.Windows.Documents.ITextPointer, System.Windows.Documents.LogicalDirection, Boolean)
   at System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.GetInsertionPosition(System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextRangeBase.CreateNormalizedTextSegment(System.Windows.Documents.ITextRange, System.Windows.Documents.ITextPointer, System.Windows.Documents.ITextPointer)
   at System.Windows.Documents.TextRangeBase.SelectPrivate(System.Windows.Documents.ITextRange, System.Windows.Documents.ITextPointer, System.Windows.Documents.ITextPointer, Boolean, Boolean)
   at System.Windows.Documents.TextRangeBase.Select(System.Windows.Documents.ITextRange, System.Windows.Documents.ITextPointer, System.Windows.Documents.ITextPointer, Boolean)
   at MajdataEdit.MainWindow.GetRawFumenText()
   at MajdataEdit.MainWindow+<SyntaxCheck>d__100.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[MajdataEdit.MainWindow+<SyntaxCheck>d__100, MajdataEdit, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null]](<SyntaxCheck>d__100 ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[MajdataEdit.MainWindow+<SyntaxCheck>d__100, MajdataEdit, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null]](<SyntaxCheck>d__100 ByRef)
   at MajdataEdit.MainWindow.SyntaxCheck()
   at MajdataEdit.MainWindow.ChartChangeTimer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)
   at System.Timers.Timer.MyTimerCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr, IntPtr)
   at System.Threading.UnmanagedThreadPoolWorkItem.ExecuteUnmanagedThreadPoolWorkItem(IntPtr, IntPtr)
   at System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by RayZXR** [comment]
我也遇到这个问题了😭Majdata-4.4.0的MajdataEdit非常频繁地闪退。也没有报错，直接就闪退了。

**Comment by LingFeng-bbben** [comment]
可以先禁用语法检查 或者回退到更旧的版本
现在主要开发majplay 这边不太管得过来
